#!/bin/sh
# Generate the landing pages for the published apk feed.
#
#     generate-feed-index.sh <site-dir> <base-url>
#
# Walks <site-dir>/<release>/<arch>/ and writes an index.html at the root plus
# one per release, each carrying the exact commands for that path. The point is
# that a router owner can copy two lines instead of working out the URL layout
# from a directory listing.
#
# Plain sh and no dependencies: it runs in the deploy job on a bare runner.

set -eu

SITE="${1:?usage: generate-feed-index.sh <site-dir> <base-url>}"
BASE="${2:?usage: generate-feed-index.sh <site-dir> <base-url>}"
BASE="${BASE%/}"

KEYNAME=olcrtc-feed.pem

# HTML-escape: the values here are release numbers and architectures, but this
# is generated output served over HTTP, so do not rely on that.
esc() {
	sed -e 's/&/\&amp;/g' -e 's/</\&lt;/g' -e 's/>/\&gt;/g'
}

page_head() {
	cat <<-HTML
		<!DOCTYPE html>
		<html lang="en">
		<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>$1</title>
		<style>
		 body{font:15px/1.55 system-ui,sans-serif;max-width:52rem;margin:2.5rem auto;padding:0 1.2rem;color:#1a1a1a}
		 code,pre{font-family:ui-monospace,SFMono-Regular,Menlo,monospace}
		 pre{background:#f6f7f9;border:1px solid #e3e6ea;border-radius:6px;padding:.8rem 1rem;overflow-x:auto}
		 h1{font-size:1.5rem} h2{font-size:1.15rem;margin-top:2rem}
		 table{border-collapse:collapse;margin:.6rem 0} td,th{text-align:left;padding:.3rem .9rem .3rem 0}
		 .note{background:#fff8e1;border-left:3px solid #e0b400;padding:.7rem 1rem;margin:1.2rem 0}
		 a{color:#0b5fa5}
		</style>
		</head>
		<body>
		<h1>$1</h1>
	HTML
}

page_tail() {
	cat <<-HTML
		<hr>
		<p><small>Generated by <code>.github/scripts/generate-feed-index.sh</code>.
		Packages are built from a pinned upstream commit; see <code>UPSTREAM</code> in the repository.</small></p>
		</body>
		</html>
	HTML
}

releases="$(find "$SITE" -mindepth 1 -maxdepth 1 -type d ! -name keys -printf '%f\n' 2>/dev/null | sort -Vr || true)"

# ------------------------------------------------------------------ root page
{
	page_head "olcRTC package feed for OpenWrt"

	cat <<-HTML
		<p>A signed <code>apk</code> repository for the
		<a href="https://github.com/openlibrecommunity/olcrtc">olcRTC</a> tunnel,
		packaged as a netifd protocol so it appears under
		<em>Network &rarr; Interfaces</em> in LuCI.</p>

		<div class="note">
		<strong>OpenWrt 25.x only.</strong> Repository signing here uses
		<code>packages.adb</code>, which exists in apk. For 24.10 install the
		<code>.ipk</code> files attached to a
		<a href="https://github.com/$(printf '%s' "${BASE#https://}" | sed 's|.*github.io/||')/releases">GitHub release</a> instead.
		</div>

		<h2>Install</h2>
		<p>Trust the signing key, add the feed for your architecture, install:</p>
		<pre><code>wget -O /etc/apk/keys/$KEYNAME $BASE/keys/$KEYNAME

		echo "$BASE/&lt;release&gt;/&lt;arch&gt;/packages.adb" \\
		  &gt;&gt; /etc/apk/repositories.d/customfeeds.list

		apk update
		apk add olcrtc luci-proto-olcrtc</code></pre>
		<p>Find your architecture with <code>apk --print-arch</code>, then pick the
		matching link below.</p>

		<h2>Available</h2>
	HTML

	if [ -z "$releases" ]; then
		echo "<p>Nothing published yet.</p>"
	else
		for rel in $releases; do
			printf '<h3><a href="%s/">OpenWrt %s</a></h3>\n' \
				"$(printf '%s' "$rel" | esc)" "$(printf '%s' "$rel" | esc)"
			echo '<table><tr><th>Architecture</th><th>Feed URL</th></tr>'
			for arch in $(find "$SITE/$rel" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort); do
				[ -f "$SITE/$rel/$arch/packages.adb" ] || continue
				a="$(printf '%s' "$arch" | esc)"
				printf '<tr><td><code>%s</code></td><td><code>%s/%s/%s/</code></td></tr>\n' \
					"$a" "$BASE" "$(printf '%s' "$rel" | esc)" "$a"
			done
			echo '</table>'
		done
	fi

	cat <<-HTML
		<h2>What this tunnel cannot carry</h2>
		<p>TCP over IPv4 only. UDP, QUIC and IPv6 are <strong>rejected</strong> rather
		than allowed to leave over the clear WAN path, so some traffic visibly fails
		instead of silently escaping. That is the intended trade &mdash; see
		<code>/usr/share/olcrtc/README</code> on the device.</p>
	HTML

	page_tail
} > "$SITE/index.html"

# --------------------------------------------------------- one page per release
for rel in $releases; do
	{
		page_head "olcRTC feed &mdash; OpenWrt $(printf '%s' "$rel" | esc)"
		printf '<p><a href="%s/">&larr; all releases</a></p>\n' "$BASE"
		for arch in $(find "$SITE/$rel" -mindepth 1 -maxdepth 1 -type d -printf '%f\n' | sort); do
			[ -f "$SITE/$rel/$arch/packages.adb" ] || continue
			a="$(printf '%s' "$arch" | esc)"
			printf '<h2>%s</h2>\n<pre><code>wget -O /etc/apk/keys/%s %s/keys/%s\n\necho "%s/%s/%s/packages.adb" \\\n  &gt;&gt; /etc/apk/repositories.d/customfeeds.list\n\napk update\napk add olcrtc luci-proto-olcrtc</code></pre>\n' \
				"$a" "$KEYNAME" "$BASE" "$KEYNAME" "$BASE" "$(printf '%s' "$rel" | esc)" "$a"
			echo '<p>Files:</p><ul>'
			for f in $(find "$SITE/$rel/$arch" -maxdepth 1 -type f -printf '%f\n' | sort); do
				printf '<li><a href="%s/%s/%s/%s">%s</a></li>\n' \
					"$BASE" "$(printf '%s' "$rel" | esc)" "$a" "$f" "$(printf '%s' "$f" | esc)"
			done
			echo '</ul>'
		done
		page_tail
	} > "$SITE/$rel/index.html"
done

# GitHub Pages would otherwise treat directories starting with an underscore,
# and anything Jekyll dislikes, as non-publishable. The workflow disables Jekyll
# but .nojekyll is what actually guarantees every file is served verbatim.
: > "$SITE/.nojekyll"

echo "generated $SITE/index.html and $(printf '%s\n' $releases | grep -c . || echo 0) release page(s)"
